server:
  port: 9002

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: player-service

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,metrics,prometheus"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    export:
      prometheus:
        enabled: true

  security:
    enabled: false
