server:
  port: 9003
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: match-service

management:
  endpoints:
    web:
      exposure:
        include: "info,hystrix.stream,logfile,prometheus,loggers,metrics"
      security:
        enabled: false
