server:
  port: 9003
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: match-service

management:
  security:
    enabled: false
