apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
        - name: match-service
          image: idricealy/match-service:1.0
          ports:
            - containerPort: 9003
