apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: idricealy/team-service:1.0
          ports:
            - containerPort: 9001
